//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStation.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusStation.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string areyousuretodelete {
            get {
                return ResourceManager.GetString("areyousuretodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string backtolist {
            get {
                return ResourceManager.GetString("backtolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City From.
        /// </summary>
        public static string cityfrom {
            get {
                return ResourceManager.GetString("cityfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string cityname {
            get {
                return ResourceManager.GetString("cityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City To.
        /// </summary>
        public static string cityto {
            get {
                return ResourceManager.GetString("cityto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient.
        /// </summary>
        public static string coefficient {
            get {
                return ResourceManager.GetString("coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confpassword {
            get {
                return ResourceManager.GetString("confpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Tickets.
        /// </summary>
        public static string counttickets {
            get {
                return ResourceManager.GetString("counttickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Poll.
        /// </summary>
        public static string datepoll {
            get {
                return ResourceManager.GetString("datepoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Price.
        /// </summary>
        public static string dateprice {
            get {
                return ResourceManager.GetString("dateprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty City.
        /// </summary>
        public static string emptycity {
            get {
                return ResourceManager.GetString("emptycity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Coefficient.
        /// </summary>
        public static string emptycoefficient {
            get {
                return ResourceManager.GetString("emptycoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Count of Tickets.
        /// </summary>
        public static string emptycounttickets {
            get {
                return ResourceManager.GetString("emptycounttickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Date.
        /// </summary>
        public static string emptydate {
            get {
                return ResourceManager.GetString("emptydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Date Poll.
        /// </summary>
        public static string emptydatepoll {
            get {
                return ResourceManager.GetString("emptydatepoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Date Price.
        /// </summary>
        public static string emptydateprice {
            get {
                return ResourceManager.GetString("emptydateprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Distance.
        /// </summary>
        public static string emptydistance {
            get {
                return ResourceManager.GetString("emptydistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty Email.
        /// </summary>
        public static string emptyemail {
            get {
                return ResourceManager.GetString("emptyemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty Login.
        /// </summary>
        public static string emptylogin {
            get {
                return ResourceManager.GetString("emptylogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Number.
        /// </summary>
        public static string emptynumber {
            get {
                return ResourceManager.GetString("emptynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty Password.
        /// </summary>
        public static string emptypassword {
            get {
                return ResourceManager.GetString("emptypassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Price.
        /// </summary>
        public static string emptyprice {
            get {
                return ResourceManager.GetString("emptyprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty Role.
        /// </summary>
        public static string emptyrole {
            get {
                return ResourceManager.GetString("emptyrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty: Seats.
        /// </summary>
        public static string emptyseats {
            get {
                return ResourceManager.GetString("emptyseats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: City.
        /// </summary>
        public static string errorcity {
            get {
                return ResourceManager.GetString("errorcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Coefficient .
        /// </summary>
        public static string errorcoefficient {
            get {
                return ResourceManager.GetString("errorcoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Count of Tickets.
        /// </summary>
        public static string errorcounttickets {
            get {
                return ResourceManager.GetString("errorcounttickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Distance.
        /// </summary>
        public static string errordistance {
            get {
                return ResourceManager.GetString("errordistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Email.
        /// </summary>
        public static string erroremail {
            get {
                return ResourceManager.GetString("erroremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Login.
        /// </summary>
        public static string errorlogin {
            get {
                return ResourceManager.GetString("errorlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Number.
        /// </summary>
        public static string errornumber {
            get {
                return ResourceManager.GetString("errornumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Price.
        /// </summary>
        public static string errorprice {
            get {
                return ResourceManager.GetString("errorprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Role.
        /// </summary>
        public static string errorrole {
            get {
                return ResourceManager.GetString("errorrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Seats.
        /// </summary>
        public static string errorseats {
            get {
                return ResourceManager.GetString("errorseats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Seats.
        /// </summary>
        public static string freeseats {
            get {
                return ResourceManager.GetString("freeseats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string loginname {
            get {
                return ResourceManager.GetString("loginname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password dont match.
        /// </summary>
        public static string passdontmatch {
            get {
                return ResourceManager.GetString("passdontmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string rolename {
            get {
                return ResourceManager.GetString("rolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string seats {
            get {
                return ResourceManager.GetString("seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        public static string trip {
            get {
                return ResourceManager.GetString("trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
